### PR TITLE
Add support for JSON resource files | Allow creation of language directories

### PR DESCRIPTION
**Pull request by kaldrenon**
I needed to modify your plugin in order to get the functionality I wanted for a project I was working on. I did my best to make the changes non-breaking, and I thought I'd open a Pull Request for you to add the features, if you want.

Major additions:

* Add `createLangDir` option. If this option is `true`, the output will be `dest/lang/file.html` rather than `dest/file-lang.html`
* Add support for reading JSON files in addition to JS, for defining translation resources. The JSON is parsed to a JS object and `define()`d.
* Basic info in the Readme

### CODE REVIEW

**Comment by webyom** [comment]
Hello kaldrenon, thank a lot for your idea and contribution to this plugin.

**Comment by webyom** [comment]
Hello @kaldrenon , 2 issues found after reviewing your code.
1. getJsResource function is not used.
2. Line 165 is duplicated with line 179

**Comment by kaldrenon** [comment]
@webyom Thanks for catching those!

As you might see from the commits, I was first editing the JS in `lib` before realizing the original source was CoffeeScript. When I made changes to the CoffeeScript, it looks like I made a few mistakes.

Those changes are updated in my fork; would you like me to open another pull request with them included?

**Comment by webyom** [comment]
@kaldrenon yes, please open the pull request.

**Pull request merged**
